[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "monabbirbhuiyan", email = "monabbir.179@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.20.0",
    "fastapi>=0.141.1",
    "langchain>=1.4.2",
    "langchain-openai>=1.6.3",
    "openai>=3.16.2",
    "psycopg2-binary>=2.9.13",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "sqlalchemy>=2.0.54",
    "sqlmodel>=0.0.45",
    "uvicorn>=0.53.0",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
