"""Add BetterAuth verification and account columns

Revision ID: 8b0d16e7b448
Revises: 23ab7f7615c5
Create Date: 2026-09-21 19:07:23.409693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b0d16e7b448'
down_revision: Union[str, Sequence[str], None] = '23ab7f7615c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('expiresAt', sa.DateTime(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('account', sa.Column('idToken', sa.String(), nullable=True))
    op.add_column('account', sa.Column('accessTokenExpiresAt', sa.DateTime(), nullable=True))
    op.add_column('account', sa.Column('refreshTokenExpiresAt', sa.DateTime(), nullable=True))
    op.add_column('account', sa.Column('scope', sa.String(), nullable=True))
    op.add_column('account', sa.Column('password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'password')
    op.drop_column('account', 'scope')
    op.drop_column('account', 'refreshTokenExpiresAt')
    op.drop_column('account', 'accessTokenExpiresAt')
    op.drop_column('account', 'idToken')
    op.drop_table('verification')
    # ### end Alembic commands ###
